### ISSUE TITLE
Try get brian snaily to work with renzu_multicharacter

### ISSUE THREAD

**Issue by SASRP77** [EWANZO101/Bryan-Snaily-CAD-Integration#2]
renzu multicharacter is found here it is a open source resource https://github.com/renzuzu/renzu_multicharacter

Please contact loyalvoid if you managed to link these to work.

#He would like to know where the Insert New Citizen would go in the script #

**Comment by EWANZO101** [comment]
He would like to know where the Insert New Citizen would go in the script

**Comment by EWANZO101** [comment]
This was just added today https://github.com/EWANZO101/Bryan-Snaily-CAD-Integration/blob/main/other%20scripts%20we%20support.md
